import { AfterViewInit, ElementRef, EventEmitter, OnDestroy, Renderer2 } from '@angular/core';
import { MdbAutoCompleterComponent } from '../components/mdb-auto-completer.component';
export declare class MdbAutoCompleterDirective implements AfterViewInit, OnDestroy {
    private renderer;
    private el;
    private document;
    mdbAutoCompleter: MdbAutoCompleterComponent;
    ngModelChange: EventEmitter<any>;
    clearBtnClicked: EventEmitter<any>;
    private _autocompleterInputChanges;
    private _clearButton;
    listenToClearClick: Function;
    isBrowser: boolean;
    constructor(renderer: Renderer2, el: ElementRef, platformId: string, document: any);
    private _getClosestEl;
    private _renderClearButton;
    private _setStyles;
    private _addClass;
    private _clearInput;
    _handleInput(event: any): void;
    _handleKeyDown(event: any): void;
    _handleFocusIn(): void;
    _handleBlurIn(): void;
    _handleMouseDown(): void;
    getCoords(elem: any): any;
    private _isOpen;
    private _show;
    private _hide;
    private _appendDropdownToInput;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
}
